const mockData = [
  {
    hospitalName: "milad",
    block: "2",
    province: "اردبیل",
    city: "خلخال",
    floorsUnder: "3",
    floorsOn: "4",
    createdDate: "2023-12-15T16:56:07.288Z",
    designedDate: "2023-12-15T16:56:05.588Z",
    serviceDate: "2023-12-15T16:56:09.405Z",
    latitude: "35.715298",
    longitude: "51.404343",
    bedsNumber: "3",
    impactFactor: "0.75",
    unitPrice: "12",
    soilType: "II",
    address: "dhawjkhdlk",
    floorsNo: 7,
    standardEdition: "V3",
    controlSystem: "Active Control",
    material: "Steel",
    lateralLoadResistantX: "Braced Frames",
    lateralLoadResistantY: "Braced Frames",
    vertical: true,
    plan: false,
    components: [
      {
        floorNo: "3",
        count: "5",
        component: "option1",
        cost: "8",
        isEmbraced: "false",
        serviceYears: "12",
      },
    ],
  },
];
