const mockData = [
  {
    hospitalName: "milad",
    block: "2",
    province: "اردبیل",
    city: "خلخال",
    floorsUnder: "3",
    floorsOn: "4",
    createdDate: "2023-12-15T16:56:07.288Z",
    designedDate: "2023-12-15T16:56:05.588Z",
    serviceDate: "2023-12-15T16:56:09.405Z",
    latitude: "35.715298",
    longitude: "51.404343",
    bedsNumber: "3",
    impactFactor: "0.75",
    unitPrice: "12",
    soilType: "II",
    address: "dhawjkhdlk",
    floorsNo: 7,
    standardEdition: "V3",
    controlSystem: "Active Control",
    material: "Steel",
    lateralLoadResistantX: "Braced Frames",
    lateralLoadResistantY: "Braced Frames",
    vertical: true,
    plan: false,
    components: [
      {
        floorNo: "3",
        count: "5",
        component: "option1",
        cost: "8",
        isEmbraced: "false",
        serviceYears: "12",
      },
    ],
    floors: [
      { index: -1, floor: 0, height: "12", area: "32" },
      { index: -2, floor: 0, height: "12", area: "32" },
      { index: 0, floor: 0, height: "12", area: "32" },
      { index: 1, floor: 0, height: "12", area: "32" },
      { index: 2, floor: 0, height: "12", area: "32" },
      { index: 3, floor: 0, height: "12", area: "32" },
    ],
    charts: {
      fragility: [
        { collapse: 0, extensive: 0.1, moderate: 0.2, slight: 0.1 },
        { collapse: 0.45, extensive: 0.4, moderate: 0.5, slight: 0.65 },
        { collapse: 0.65, extensive: 0.6, moderate: 0.98, slight: 0.9 },
        { collapse: 0.85, extensive: 0.9, moderate: 1, slight: 0.95 },
        { collapse: 1, extensive: 1, moderate: 1, slight: 1 },
      ],
      hazard: [
        { amplifiedHazard: null, hazard: null },
        { amplifiedHazard: 1.6, hazard: 1.4 },
        { amplifiedHazard: 0.25, hazard: 0.24 },
        { amplifiedHazard: 0.25, hazard: 0.24 },
        { amplifiedHazard: 0.25, hazard: 0.24 },
        { amplifiedHazard: 0.25, hazard: null },
        { amplifiedHazard: 0.25, hazard: null },
        { amplifiedHazard: 0.25, hazard: null },
      ],
      loss: {},
      risk: {},
    },
  },
  {
    hospitalName: "emam khomeyni",
    block: "2",
    province: "اردبیل",
    city: "خلخال",
    floorsUnder: "5",
    floorsOn: "3",
    createdDate: "2023-12-15T16:56:07.288Z",
    designedDate: "2023-12-15T16:56:05.588Z",
    serviceDate: "2023-12-15T16:56:09.405Z",
    latitude: "35.715298",
    longitude: "51.404343",
    bedsNumber: "3",
    impactFactor: "0.75",
    unitPrice: "12",
    soilType: "type II",
    address: "dhawjkhdlk",
    floorsNo: 7,
    standardEdition: "V3",
    controlSystem: "Active Control",
    material: "Steel",
    lateralLoadResistantX: "Braced Frames",
    lateralLoadResistantY: "Braced Frames",
    vertical: true,
    plan: false,
    components: [
      {
        floorNo: "3",
        count: "5",
        component: "option1",
        cost: "8",
        isEmbraced: "false",
        serviceYears: "12",
      },
    ],
    floors: [
      { index: -1, floor: 0, height: "12", area: "32" },
      { index: -2, floor: 0, height: "12", area: "32" },
      { index: 0, floor: 0, height: "12", area: "32" },
      { index: 1, floor: 0, height: "12", area: "32" },
      { index: 2, floor: 0, height: "12", area: "32" },
      { index: 3, floor: 0, height: "12", area: "32" },
    ],
    charts: {
      fragility: [
        { collapse: 0, extensive: 0.0, moderate: 0.0, slight: 0.0 },
        { collapse: 0.45, extensive: 0.6, moderate: 0.7, slight: 0.65 },
        { collapse: 0.65, extensive: 0.8, moderate: 0.9, slight: 0.85 },
        { collapse: 0.85, extensive: 0.9, moderate: 1, slight: 0.95 },
        { collapse: 1, extensive: 1, moderate: 1, slight: 1 },
      ],
      hazard: [
        { amplifiedHazard: null, hazard: null },
        { amplifiedHazard: 1.6, hazard: 1.4 },
        { amplifiedHazard: 0.25, hazard: 0.24 },
        { amplifiedHazard: 0.25, hazard: 0.24 },
        { amplifiedHazard: 0.25, hazard: 0.24 },
        { amplifiedHazard: 0.25, hazard: null },
        { amplifiedHazard: 0.25, hazard: null },
        { amplifiedHazard: 0.25, hazard: null },
      ],
      loss: {},
      risk: {},
    },
  },
  {
    hospitalName: "emam ali",
    block: "2",
    province: "اردبیل",
    city: "خلخال",
    floorsUnder: "3",
    floorsOn: "4",
    createdDate: "2023-12-15T16:56:07.288Z",
    designedDate: "2023-12-15T16:56:05.588Z",
    serviceDate: "2023-12-15T16:56:09.405Z",
    latitude: "35.715298",
    longitude: "51.404343",
    bedsNumber: "3",
    impactFactor: "0.75",
    unitPrice: "12",
    soilType: "type II",
    address: "dhawjkhdlk",
    floorsNo: 7,
    standardEdition: "V3",
    controlSystem: "Active Control",
    material: "Steel",
    lateralLoadResistantX: "Braced Frames",
    lateralLoadResistantY: "Braced Frames",
    vertical: true,
    plan: false,
    components: [
      {
        floorNo: "3",
        count: "5",
        component: "option1",
        cost: "8",
        isEmbraced: "false",
        serviceYears: "12",
      },
    ],
    floors: [
      { index: -1, floor: 0, height: "12", area: "32" },
      { index: -2, floor: 0, height: "12", area: "32" },
      { index: 0, floor: 0, height: "12", area: "32" },
      { index: 1, floor: 0, height: "12", area: "32" },
      { index: 2, floor: 0, height: "12", area: "32" },
      { index: 3, floor: 0, height: "12", area: "32" },
    ],
    charts: {
      fragility: [
        { collapse: 0, extensive: 0.0, moderate: 0.0, slight: 0.0 },
        { collapse: 0.45, extensive: 0.6, moderate: 0.7, slight: 0.65 },
        { collapse: 0.65, extensive: 0.8, moderate: 0.9, slight: 0.85 },
        { collapse: 0.85, extensive: 0.9, moderate: 1, slight: 0.95 },
        { collapse: 1, extensive: 1, moderate: 1, slight: 1 },
      ],
      hazard: [
        { amplifiedHazard: null, hazard: null },
        { amplifiedHazard: 1.6, hazard: 1.4 },
        { amplifiedHazard: 0.3, hazard: 0.4 },
        { amplifiedHazard: 0.3, hazard: 0.4 },
        { amplifiedHazard: 0.3, hazard: 0.4 },
        { amplifiedHazard: 0.3, hazard: null },
        { amplifiedHazard: 0.3, hazard: null },
        { amplifiedHazard: 0.3, hazard: null },
      ],
      loss: {},
      risk: {},
    },
  },
  {
    hospitalName: "emam hosein",
    block: "2",
    province: "اردبیل",
    city: "خلخال",
    floorsUnder: "3",
    floorsOn: "4",
    createdDate: "2023-12-15T16:56:07.288Z",
    designedDate: "2023-12-15T16:56:05.588Z",
    serviceDate: "2023-12-15T16:56:09.405Z",
    latitude: "35.715298",
    longitude: "51.404343",
    bedsNumber: "3",
    impactFactor: "0.75",
    unitPrice: "12",
    soilType: "type II",
    address: "dhawjkhdlk",
    floorsNo: 7,
    standardEdition: "V3",
    controlSystem: "Active Control",
    material: "Steel",
    lateralLoadResistantX: "Braced Frames",
    lateralLoadResistantY: "Braced Frames",
    vertical: true,
    plan: false,
    components: [
      {
        floorNo: "3",
        count: "5",
        component: "option1",
        cost: "8",
        isEmbraced: "false",
        serviceYears: "12",
      },
    ],
    floors: [
      { index: -1, floor: 0, height: "12", area: "32" },
      { index: -2, floor: 0, height: "12", area: "32" },
      { index: 0, floor: 0, height: "12", area: "32" },
      { index: 1, floor: 0, height: "12", area: "32" },
      { index: 2, floor: 0, height: "12", area: "32" },
      { index: 3, floor: 0, height: "12", area: "32" },
    ],
    charts: {
      fragility: [
        { collapse: 0, extensive: 0.0, moderate: 0.0, slight: 0.0 },
        { collapse: 0.45, extensive: 0.6, moderate: 0.8, slight: 0.65 },
        { collapse: 0.65, extensive: 0.8, moderate: 0.95, slight: 0.85 },
        { collapse: 0.85, extensive: 0.9, moderate: 1.5, slight: 0.98 },
        { collapse: 1, extensive: 1, moderate: 1, slight: 1 },
      ],
      hazard: [
        { amplifiedHazard: null, hazard: null },
        { amplifiedHazard: 1.6, hazard: 1.6 },
        { amplifiedHazard: 0.28, hazard: 0.2 },
        { amplifiedHazard: 0.28, hazard: 0.2 },
        { amplifiedHazard: 0.28, hazard: 0.2 },
        { amplifiedHazard: 0.28, hazard: null },
        { amplifiedHazard: 0.28, hazard: null },
        { amplifiedHazard: 0.28, hazard: null },
      ],
      loss: {},
      risk: {},
    },
  },
];
export default mockData;
